Edge case handled for when values yaml to be used is unspecified
Asimmetric/chart-library pull request #15
Opened 2021-08-19 00:50 UTC by amitghetiya

When "-f values-staging.yaml" is not used as argument, the serviceaccount template was getting a nil error because it was finding annotations in wrong values file.

2021-08-19 06:41 UTC, avoid3d approved these changes
LGTM

2021-08-19 06:52 UTC, deontpearson commented on charts/serviceaccountlib/templates/_serviceaccount.tpl
> +  {{ if .Values.serviceAccount }}
You might need to rather check for ` .Values.serviceAccount.annotations` rather than just `.Values.serviceAccount`

2021-08-19 06:53 UTC, deontpearson submitted a review, later dismissed
@amitghetiya you are getting that error because helm looks for the default `values.yaml` file to template the charts. When you add `-f values-staging.yaml` to the template process you are telling helm to use the `values.yaml` file and then override any values with the ones defined in `values-staging.yaml`. 

In your serviceaccountexample you only define the `serviceAccount` mapping in `values-staging.yaml`. May I suggest the following changes:

1. In serviceaccountexample remove the `values.yaml file` and rename `values-staging.yaml` to `values.yaml`. Also remove the env mapping its not need for this example
2. From the new `values.yaml` file remove `serviceAccount.create` because you do not use this and also you say whether you want to create a service account by either adding the `serviceaccount.yaml` file to the `templates` folder or not.
3.  From the new `values.yaml` file remove `serviceAccount.name` because it is not being used. The service account gets its name from `{{ .Chart.Name }}` 
4. Rename the `serviceAccount` mapping to `serviceAccountAnnotations` and then change your check from `{{ if .Values.serviceAccount }}` to `{{ if .Values.serviceAccountAnnotations }}`

2021-08-19 07:05 UTC, deontpearson requested changes
see comment

2021-09-16 20:32 UTC, amitghetiya commented
Closing this because required changes were incorporated in brandon's PR

2021-09-16 20:32 UTC, closed without merging